# -*- coding: utf-8 -*-
"""Combinacion_ordinaria.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mmkHkX5KhO0mo85gJLQBVz2pufpIRaJR
"""

def combinations(n, k):
  if k > n:
    return
  comb = []
  def backtrack(first=1):
    if len(comb) == k:
      yield comb.copy()
      return
    for i in range(first, n+1):
      comb.append(i)
      yield from backtrack(i+1)
      comb.pop()
  count = 0
  for c in backtrack():
    count += 1
    print(count, c)
  print("Numero de combinaciones ", count) 

combinations(5,3)